const fs = require('fs');
let code = fs.readFileSync('./src/components/LiveScoring.tsx', 'utf-8');

const oldFlow = "                <div className=\"bg-slate-100 p-4 rounded-lg font-mono text-[10px] text-slate-600 whitespace-pre\">\n{`Professional Camera\n        │\n HDMI / SDI\n        │\n Capture Card\n        │\n Laptop\n        │\nOBS / vMix\n        │\n RTMP\n        │\n Streaming Server\n        │\n Streamlify Live\n        │\n Viewers`}\n                </div>";

const newFlow = "                <div className=\"bg-slate-100 p-4 rounded-lg font-mono text-[10px] text-slate-600 whitespace-pre\">\n{`Professional Camera\n        │\n HDMI / SDI\n        │\n Capture Card\n        │\n Laptop\n        │\n    OBS Studio ───────────┐\n        │                 │\n RTMP to YouTube Live     │ Custom OBS Plugin\n        │                 │ (Streamlify Sync)\n YouTube URL pasted       │\n   in Streamlify          │\n        │                 │\n     Viewers <────────────┘\n`}\n                </div>\n                <div className=\"mt-4 border-t border-slate-200 pt-4\">\n                  <h4 className=\"font-bold text-slate-800 flex items-center mb-2\"><Download className=\"w-4 h-4 mr-2 text-indigo-600\" /> Streamlify OBS Plugin</h4>\n                  <p className=\"text-xs text-slate-600 mb-3\">\n                    Download our custom OBS plugin to automatically sync live scores, wickets, and match events as dynamic text sources in OBS Studio.\n                  </p>\n                  <div className=\"flex space-x-3\">\n                    <a href=\"#\" onClick={(e) => { e.preventDefault(); alert('Downloading OBS Plugin for Windows...'); }} className=\"flex-1 bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-3 rounded text-xs font-bold text-center transition-colors shadow-sm\">\n                      Download for Windows (.exe)\n                    </a>\n                    <a href=\"#\" onClick={(e) => { e.preventDefault(); alert('Downloading OBS Plugin for macOS...'); }} className=\"flex-1 bg-slate-800 hover:bg-slate-900 text-white py-2 px-3 rounded text-xs font-bold text-center transition-colors shadow-sm\">\n                      Download for macOS (.pkg)\n                    </a>\n                  </div>\n                  <p className=\"text-[9px] text-slate-400 mt-2\">Version 1.2.0 • Requires OBS Studio 28.0+</p>\n                </div>";

code = code.replace(oldFlow, newFlow);

fs.writeFileSync('./src/components/LiveScoring.tsx', code);
